version: '3.8'

services:
  fuhagen_1:
    build: .
    volumes:
      - .:/app
    command: python src/main.py

  jupyter:
    build: .
    volumes:
      - ./src:/home/jovyan/work
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: jupyter lab --notebook-dir=/home/jovyan/work --ip='0.0.0.0' --port=8888 --no-browser --allow-root
