version: '3.8'

services:
  fuhagen_1:
    build: .
    volumes:
      - .:/app
    command: python src/main.py

  jupyter:
    image: jupyter/base-notebook:latest
    volumes:
      - ./src:/home/jovyan/work
    ports:
      - "8888:8888"
    # Enable JupyterLab interface 
    environment:
      - JUPYTER_ENABLE_LAB=yes
